### PR TITLE
restart buildbot after config-change

### PR DESCRIPTION
**Pull request by SvenRoederer**
according to https://git-scm.com/docs/githooks#_post_merge the post-merge hook is called after "git pull" ran to update the local repo. As this script is not in the default "git-hooks"- directory ($GIT_DIR/hooks) it can be activated by one of:
* set "core.hooksPath" to "git-hooks"
* symlink the script to "$GIT_DIR/hooks/post-merge"

This post-merge script will restart the buildbot-daemon to apply the new config provided in the repo.
This can be combined with a cronjob to do "git pull" and we have some git-controlled autodeploy.

### CODE REVIEW

**Comment by sarumpaet** [comment]
Is this intended for the buildbot master? If yes, this would be quite a security problem, as it would effectively give all Git contributors full access to the buildbot including already built firmware images, right? What if one of those 20 people's machines gets hacked?

**Comment by SvenRoederer** [comment]
I would prefer, to keep the discussion in one place. This should be the mailinglist, as it was started there: https://lists.berlin.freifunk.net/pipermail/berlin/2018-April/037566.html

**Comment by sarumpaet** [comment]
The mailinglist is more an end-user thing, isn't it? Also, it'd be weird to have the discussion for a PR somewhere else.

> Even if a machine get hacked, the github password will be needed
No. For a commit/push to master, clearly only the SSH key is needed.

> And the "hacker" even has to use a git-commit to push evil code, which will be seen by everyone
Pushes don't create GitHub notifications, and it's easy to revert invisibly by force-pushing the old state.

Buildbot/firmware downloads are one of the most security crucial things we manage, and we shouldn't auto-deploy code there via Git/cronjobs. What's the problem with one person doing the pull manually? It's not like the buildbot master has to have its config updated every day (in fact, for reproduceability it certainly shouldn't).

**Comment by SvenRoederer** [comment]
As of the obviously unmaintained buildbot and switching to GitHubActions (after merge of https://github.com/freifunk-berlin/firmware/pull/839  in https://github.com/freifunk-berlin/firmware/commit/0bd3b45a4bc289075ef1909ea396ad0fcd52d037), we can control the CI-behaviour easily from then firmware-repo. So this PR is obsolete and I close it.

**Pull request closed without merging**
